data_ingestion:
  root_dir: artifacts/data_ingestion
  huggingface_source_url: OSS-forge/PyResBugs
  local_data_file: artifacts/data_ingestion/PyresBugs.tsv

data_validation:
  root_dir: artifacts/data_validation
  status_file: artifacts/data_validation/status.txt
  all_required_files: ["artifacts/data_ingestion/PyresBugs.tsv"]

data_transformation:
  root_dir: artifacts/data_transformation
  source_data_file: artifacts/data_ingestion/PyresBugs.tsv
  tokenizer_name: Qwen/Qwen2.5-Coder-3B-Instruct
  max_length: 1024
  test_size: 0.1

model:
  root_dir: artifacts/model
  model_name: Qwen/Qwen2.5-Coder-3B-Instruct
  cache_dir: /home/muggle/.cache/huggingface/hub
  use_4bit: true

training:
  root_dir: artifacts/training
  dataset_path: artifacts/data_transformation
  num_train_epochs: 3
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 8
  learning_rate: 2e-4
  logging_steps: 25
  save_steps: 100
  eval_steps: 100
  warmup_ratio: 0.05
  lora_r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]
